# Google Cloud Build configuration for WA-Brains
steps:
  # Step 1: Install dependencies
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['ci', '--only=production']
    env:
      - 'NODE_ENV=production'

  # Step 2: Build the application
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']
    env:
      - 'NODE_ENV=production'
      - 'VITE_SUPABASE_URL=https://kherttvqpbqjqjveyvll.supabase.co'
      - 'VITE_SUPABASE_PUBLISHABLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtoZXJ0dHZxcGJxanFqdmV5dmxsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NDMwNDQsImV4cCI6MjA3MzExOTA0NH0.OCyN_CpLadiJGU_RpkidXYtmkHyAgAJ30LbJ3JeO5tc'

  # Step 3: Deploy to App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['app', 'deploy', '--quiet']

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Timeout (10 minutes)
timeout: 600s

# Substitutions for different environments
substitutions:
  _ENVIRONMENT: 'production'

# Build artifacts
artifacts:
  objects:
    location: 'gs://${PROJECT_ID}_cloudbuild'
    paths: ['dist/**/*']